"""init

Revision ID: e20ba1d40225
Revises: 6e8b50d3b118
Create Date: 2020-04-07 11:36:41.708374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20ba1d40225'
down_revision = '6e8b50d3b118'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('email_confirmation_sent_on', sa.Text(), nullable=True),
    sa.Column('email_confirmed', sa.Integer(), nullable=True),
    sa.Column('email_confirmed_on', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
