"""init

Revision ID: bec382859e50
Revises: a8eb038e4dfa
Create Date: 2020-05-22 13:35:30.977800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec382859e50'
down_revision = 'a8eb038e4dfa'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
