"""init

Revision ID: a8eb038e4dfa
Revises: e20ba1d40225
Create Date: 2020-05-22 12:45:11.374670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8eb038e4dfa'
down_revision = 'e20ba1d40225'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_password', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('temp_password_confirmed_on', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('temp_password_sent', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_password_sent')
    op.drop_column('users', 'temp_password_confirmed_on')
    op.drop_column('users', 'temp_password')
    # ### end Alembic commands ###
